#!/usr/bin/env python3

# =============================================================
# MODEL — METHOD 2 V3
# =============================================================
# Improvements over V1/V2:
#   1. 9 input features instead of 5:
#      + kappa_la_5, kappa_la_10, kappa_la_20, kappa_la_30 (4 lookahead curvatures)
#      + vy (lateral velocity — grip/slide proxy)
#   2. Deeper network: 9 → 128 → 128 → 64 → 32 → 1
#   3. Training data includes mirrored augmentation (~2x samples)
#
# Dataset   : method2V3_data.csv  (generated by extract_data_method2V3.py)
# Model out : models_path/method2_modelV3_best.pth
# Scaler out: models_path/scaler_V3.save
# =============================================================

import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import joblib
import matplotlib.pyplot as plt
import os

# =============================================================
# STEP 1 — LOAD DATASET
# =============================================================
DATA_PATH = "/home/sanjeev/f110_ws/src/Data/data_files/method2V3_data.csv"

if not os.path.exists(DATA_PATH):
    raise FileNotFoundError(
        f"Dataset not found: {DATA_PATH}\n"
        f"Run extract_data_method2V3.py first to generate it."
    )

df = pd.read_csv(DATA_PATH)
print(f"✅ Loaded dataset | Rows: {len(df)}")
print(f"   Columns: {list(df.columns)}")

# =============================================================
# STEP 2 — FEATURES AND LABEL
# 9 input features, 1 output
# =============================================================
FEATURE_COLS = [
    "d_m",
    "heading_error",
    "kappa",
    "vx",
    "kappa_la_5",
    "kappa_la_10",
    "kappa_la_20",
    "kappa_la_30",
    "vy"
]

X = df[FEATURE_COLS].values
y = df[["steering"]].values

print(f"   X shape : {X.shape}")
print(f"   y shape : {y.shape}")

# =============================================================
# STEP 3 — NORMALIZE FEATURES
# Scaler saved separately from V1 — do NOT overwrite V1 scaler
# =============================================================
SCALER_OUT = "/home/sanjeev/f110_ws/src/ML_controller/models_path/scaler_V3.save"

scaler = StandardScaler()
X = scaler.fit_transform(X)
joblib.dump(scaler, SCALER_OUT)
print(f"✅ Scaler saved: {SCALER_OUT}")

# =============================================================
# STEP 4 — TRAIN / VAL SPLIT
# =============================================================
X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

print(f"   Train: {len(X_train)} | Val: {len(X_val)}")

# =============================================================
# STEP 5 — TENSORS
# =============================================================
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
X_val   = torch.tensor(X_val,   dtype=torch.float32)
y_val   = torch.tensor(y_val,   dtype=torch.float32)

# =============================================================
# STEP 6 — MODEL DEFINITION
# Wider + deeper than V1 to handle 9 input features
# 9 → 128 → 128 → 64 → 32 → 1
# =============================================================
class SteeringModelV3(nn.Module):
    def __init__(self):
        super(SteeringModelV3, self).__init__()

        self.net = nn.Sequential(

            nn.Linear(9, 128),
            nn.ReLU(),
            nn.Dropout(0.2),

            nn.Linear(128, 128),
            nn.ReLU(),
            nn.Dropout(0.2),

            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.1),

            nn.Linear(64, 32),
            nn.ReLU(),

            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.net(x)


model = SteeringModelV3()

total_params = sum(p.numel() for p in model.parameters())
print(f"\n✅ Model V3 | Parameters: {total_params}")

# =============================================================
# STEP 7 — LOSS, OPTIMIZER, SCHEDULER
# =============================================================
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode='min',
    patience=100,
    factor=0.5,
    verbose=True
)

# =============================================================
# STEP 8 — EARLY STOPPING SETUP
# =============================================================
EARLY_STOP_PATIENCE = 200
best_val_loss       = float('inf')
epochs_no_improve   = 0

MODEL_OUT = "/home/sanjeev/f110_ws/src/ML_controller/models_path/method2_modelV3_best.pth"

# =============================================================
# STEP 9 — TRAINING LOOP
# =============================================================
EPOCHS     = 2000
BATCH_SIZE = 256

train_loss_history = []
val_loss_history   = []

print(f"\n{'='*60}")
print(f"  Training V3 | Epochs: {EPOCHS} | Batch: {BATCH_SIZE}")
print(f"{'='*60}\n")

for epoch in range(EPOCHS):

    # ===== TRAIN =====
    model.train()
    perm       = torch.randperm(X_train.size(0))
    train_loss = 0.0

    for i in range(0, X_train.size(0), BATCH_SIZE):
        idx     = perm[i:i + BATCH_SIZE]
        batch_x = X_train[idx]
        batch_y = y_train[idx]

        optimizer.zero_grad()
        loss = criterion(model(batch_x), batch_y)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()

    train_loss /= max(1, X_train.size(0) // BATCH_SIZE)

    # ===== VALIDATION =====
    model.eval()
    with torch.no_grad():
        val_loss = criterion(model(X_val), y_val).item()

    scheduler.step(val_loss)
    train_loss_history.append(train_loss)
    val_loss_history.append(val_loss)

    # ===== EARLY STOPPING =====
    if val_loss < best_val_loss:
        best_val_loss     = val_loss
        epochs_no_improve = 0
        torch.save(model.state_dict(), MODEL_OUT)
    else:
        epochs_no_improve += 1

    if epochs_no_improve >= EARLY_STOP_PATIENCE:
        print(f"\n⚠️  Early stopping at epoch {epoch+1} | Best Val Loss: {best_val_loss:.6f}")
        break

    if (epoch + 1) == 1 or (epoch + 1) % 50 == 0:
        print(f"Epoch {epoch+1:>4}/{EPOCHS} | "
              f"Train: {train_loss:.6f} | "
              f"Val: {val_loss:.6f} | "
              f"Best: {best_val_loss:.6f} | "
              f"LR: {optimizer.param_groups[0]['lr']:.6f}")

# =============================================================
# STEP 10 — SAVE FINAL + PLOT
# =============================================================
final_path = MODEL_OUT.replace("_best", "_final")
torch.save(model.state_dict(), final_path)

print(f"\n✅ Best model  : {MODEL_OUT}")
print(f"✅ Final model : {final_path}")
print(f"✅ Best val loss: {best_val_loss:.6f}")

plt.figure(figsize=(12, 5))
plt.plot(train_loss_history, label='Train Loss', color='steelblue')
plt.plot(val_loss_history,   label='Val Loss',   color='orange')
plt.xlabel('Epoch')
plt.ylabel('MSE Loss')
plt.title('Training Curve — Model V3 (9 features + augmentation)')
plt.legend()
plt.grid(True)
plt.tight_layout()
plot_path = "/home/sanjeev/f110_ws/src/Data/plots&fig/training_curve_V3.png"
plt.savefig(plot_path)
plt.show()
print(f"✅ Training curve saved: {plot_path}")
